services:
  - type: web
    name: schedula-api
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run migration:run:prod && npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
